- name: Restart systemd-networkd
  shell: |
    (
      sleep 0.3
      ip link delete "{{ wg_iface_name }}"
      sleep 0.3
      systemctl restart systemd-networkd
    ) &
    wait
  args:
    executable: /bin/bash


- name: "Enable and restart wg-quick@{{ wg_iface_name }}.service"
  systemd:
    name: "wg-quick@{{ wg_iface_name }}.service"
    enabled: yes
    scope: system
    state: restarted

